### ISSUE TITLE
Dart websocket clinet

### ISSUE THREAD

**Issue by suyulin** [Theldus/wsServer#19] opened 2021-03-03 14:16 UTC
hi,
dart websocket client connect error
`  HttpException: Connection closed before full header was received`

**Comment by Theldus** [comment] 2021-03-03 18:53
Hi @suyulin,
I have no experience with Dart, could you provide me with all the necessary steps to reproduce this issue?

**Comment by Theldus** [comment] 2021-05-26 02:23
It's been 2 months since my last reply and I didn't get any feedback, so I'm closing this issue.

**Closed by Theldus** 2021-05-26 02:23 UTC
