### ISSUE TITLE
How to close the connection at server side?

### ISSUE THREAD

**Issue by zatarus** [Theldus/wsServer#12] opened 2020-12-11 09:14 UTC
Pardon me if an obvious question.. Having fd on hand, is there a way to manually close connection before client hits 'disconnect' ? Thank you

**Comment by Theldus** [comment] 2020-12-11 16:13
Hello @zatarus, that's a good question,
At this point, wsServer has no routine that arbitrarily closes the client connection. A quick fix that you may have guessed is just call the `close()` function passing the fd client, but this is not the correct way to do it.

The proper way would be for the server to send a close frame to the client and then initiate a closing handshake and only then terminate the connection; maybe I should work on it, since it's something really useful to have.

**Comment by zatarus** [comment] 2020-12-11 16:34
Hey @Theldus, that's good to know. I will probably signal the client with a 'close' message as a workaround until that becomes available. Cheers

**Comment by zatarus** [comment] 2020-12-11 16:35
Hey @Theldus, that's good to know. I will probably signal the client with a 'close' message as a workaround (so it can be triggered from js side), until if any api becomes available. Cheers

**Comment by Theldus** [comment] 2020-12-21 05:08
Hey @zatarus,
I've made a PR (#13) that adds the routine `ws_close_client`with the following signature:
```c
int ws_close_client(int fd);
```
that receives a client `fd`and returns 0 if success, -1 otherwise. I hope this routine meets your expectations, ;-).

**Closed** 2020-12-21 05:11 UTC

**Comment by zatarus** [comment] 2020-12-24 14:07
Thank you @Theldus, I will be switching over to this function instead of telling clients to disconnect. Cheers!

**Comment by nikto-b** [comment] 2025-01-29 18:48
Looks like calling `ws_close_client` causes firing `onclose` with invalid client and server context. Is this expected behavior?

**Comment by Theldus** [comment] 2025-02-03 00:47
Hi @nikto-b,
Sorry for the late reply,
This is certainly not expected!, do you have a minimal reproducible example where this happens?
