### ISSUE TITLE
Compile on Windows?

### ISSUE THREAD

**Issue by smilexs4** [Theldus/wsServer#9] opened 2020-10-26 21:14 UTC
Hi! I tried to compile the library on Windows by changing sys/socket.h and arpa/inet.h includes to winsock2.h and ws2tcpip.h, but failed. Can you help with them? Thank You!
```
libws.a(ws.c.obj):ws.c:(.text+0x22): undefined reference to `getpeername@12'
libws.a(ws.c.obj):ws.c:(.text+0x4a): undefined reference to `inet_ntoa@4'
libws.a(ws.c.obj):ws.c:(.text+0x5c9): undefined reference to `socket@12'
libws.a(ws.c.obj):ws.c:(.text+0x61e): undefined reference to `setsockopt@20'
libws.a(ws.c.obj):ws.c:(.text+0x656): undefined reference to `htons@4'
libws.a(ws.c.obj):ws.c:(.text+0x677): undefined reference to `bind@12'
libws.a(ws.c.obj):ws.c:(.text+0x6a9): undefined reference to `listen@8'
libws.a(ws.c.obj):ws.c:(.text+0x6f4): undefined reference to `accept@12'
collect2.exe: error: ld returned 1 exit status
CMakeFiles\send_receive.dir\build.make:105: recipe for target 'send_receive.exe' failed
mingw32-make[2]: *** [send_receive.exe] Error 1
CMakeFiles\Makefile2:122: recipe for target 'CMakeFiles/send_receive.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/send_receive.dir/all] Error 2
Makefile:101: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

**Comment by Theldus** [comment] 2020-10-27 03:34
Hi @smilexs4, glad you're giving a try to this project,
I had to confess that I never tested this project in Windows environments. I would be surprised if it worked without modifications.

Could you provide me with more details about your environment? such as:
- Windows version (7, 10, etc)
- Architecture (x86 / x86_64, although that shouldn't be important)
- Which compiler used? MinGW, Cygwin, WSL, Visual Studio...?

I want to reproduce your error here and try to work on it, but as I have no experience in Windows environments, I need the information above to study how I can help you.

\* I am _almost_ sure it would work without modifications in Cygwin since they try their best to get close to a Linux and POSIX environment, might be worth a try.

**Comment by smilexs4** [comment] 2020-10-27 07:26
I am using Windows 10 x86_64. Steps to reproduce the error:

- Download and extract the library from [https://github.com/Theldus/wsServer](url)

- Create a folder called "build" inside the extracted library.

- `cmake -G "MinGW Makefiles" ..` (requires CMake installed and set to PATH)

- `mingw32-make` (requires MinGW installed and set to PATH)

This produces the following error:

```wsServer-master\src\ws.c:17:24: fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h>
                        ^
compilation terminated.
CMakeFiles\ws.dir\build.make:81: recipe for target 'CMakeFiles/ws.dir/src/ws.c.obj' failed
mingw32-make[2]: *** [CMakeFiles/ws.dir/src/ws.c.obj] Error 1
CMakeFiles\Makefile2:95: recipe for target 'CMakeFiles/ws.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/ws.dir/all] Error 2
Makefile:101: recipe for target 'all' failed
mingw32-make: *** [all] Error 2```

After changing sys/socket.h and arpa/inet.h includes to winsock2.h and ws2tcpip.h in ws.c (I read these are alternatives for Windows) the error is the same as the one posted in my first comment:

```
libws.a(ws.c.obj):ws.c:(.text+0x22): undefined reference to `getpeername@12'
libws.a(ws.c.obj):ws.c:(.text+0x4a): undefined reference to `inet_ntoa@4'
libws.a(ws.c.obj):ws.c:(.text+0x5c9): undefined reference to `socket@12'
libws.a(ws.c.obj):ws.c:(.text+0x61e): undefined reference to `setsockopt@20'
libws.a(ws.c.obj):ws.c:(.text+0x656): undefined reference to `htons@4'
libws.a(ws.c.obj):ws.c:(.text+0x677): undefined reference to `bind@12'
libws.a(ws.c.obj):ws.c:(.text+0x6a9): undefined reference to `listen@8'
libws.a(ws.c.obj):ws.c:(.text+0x6f4): undefined reference to `accept@12'
collect2.exe: error: ld returned 1 exit status
CMakeFiles\send_receive.dir\build.make:105: recipe for target 'send_receive.exe' failed
mingw32-make[2]: *** [send_receive.exe] Error 1
CMakeFiles\Makefile2:122: recipe for target 'CMakeFiles/send_receive.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/send_receive.dir/all] Error 2
Makefile:101: recipe for target 'all' failed
mingw32-make: *** [all] Error 2```

**Comment by Theldus** [comment] 2020-10-27 20:12
Hi,
Curious that you didn't say that there were problems with pthread. It should have happened, since Windows does not support pthreads natively, and MinGW does not even provide headers for this. I was able to get around here using the 'pthreads_win32' library, which adds a series of wrappers for the POSIX routines to the Windows equivalents.

However, as you well pointed out, there are also some issues with these network routines. The 'undefined references' I was able to solve by adding the ws2_32.dll to the list of dependencies in CMakeLists.txt, however, I'm still having some execution problems with the server: it seems that the behavior of Windows socket routines does not have the same behavior as Linux (and POSIX) and require some extra steps (such as a call to WSAStartup before creating the socket), which I'm still trying to understand.

Taking all of this into account, I would like to ask you if Cygwin _really_ does not meet your needs. I was able to compile and run on Windows without _any_ modifications to the wsServer source code. The only practical difference is that programs compiled with Cygwin require some Cygwin DLLs for proper functioning (like cygwin1.dll) while compiled projects that use MinGW don't. However, given the ease, I believe it is fair enough.

What are your thoughts on this?

**Comment by smilexs4** [comment] 2020-10-27 21:13
Hi,
The final program would run on linux, however I would like to use Visual Studio while debugging on Windows. Maybe is it possible to use Cygwin inside Visual Studio?
Also, could you share CMakeLists.txt that contains ws2_32.dll? Then maybe I can try some changes in the code. Thank you!

**Comment by Theldus** [comment] 2020-10-28 13:23
Hi,
> The final program would run on linux, however I would like to use Visual Studio while debugging on Windows. 

So, you want to run on Linux and debug on Windows? is it right? If so, why not debug directly on Linux, instead? Cygwin also have GDB if you want to stick on Windows.

> Maybe is it possible to use Cygwin inside Visual Studio?

Looks like it's possible via: [Using Visual Studio to debug Cygwin applications](https://visualgdb.com/tutorials/cygwin/), I haven't tested here, though.

> Edit: I managed to compile. After compiling and running the port is open but connections are not accepted.

That's exactly where I'm stucked in, not accepting connections here too. Just one question, what did you do to overcome the pthreads issue? have you implemented/ported all the threading routines, or maybe used the pthreads_win32?

**Comment by smilexs4** [comment] 2020-10-28 13:34
> That's exactly where I'm stucked in, not accepting connections here too. Just one question, what did you do to overcome the pthreads issue? have you implemented/ported all the threading routines, or maybe used the pthreads_win32?

I used `-lpthread` or `-pthread` (not sure) argument with gcc.

> Looks like it's possible via: Using Visual Studio to debug Cygwin applications, I haven't tested here, though.

I am trying get WSL working in Visual Studio Code. So far it seems to compile but without the include path and static link library set it fails, I have to figure these out. I might give a try to your suggestion with Cygwin too.

**Comment by Theldus** [comment] 2020-10-28 15:38
Hi @smilexs4,
Good news, I figured out what was doing wrong: the return value for `accept()` is expected to be used only on socket routines, not `read()/write()` routines as wsServer does (and works on Linux systems). Besides that, you also need to invoke `WSAStartup()` before creating the socket.

Anyway, I've pushed a new branch, called 'draft_windows' contains all the needed modifications (I hope) to run on Windows environments. Follow the steps below on your command prompt:

```bash
git clone https://github.com/Theldus/wsServer.git
cd wsServer/
git checkout draft_windows
mkdir build
cd build/
cmake -G "MinGW Makefiles" ..
mingw32-make

# And finally
send_receive.exe
```
you can test it by opening the send_receive.html file in the examples/ folder.

---
> Edit: adding "-I","${fileDirname}/../include","-pthread","${fileDirname}/../build/libws.a" values to tasks.json in Visual Studio Code does the trick.

Natively or on WSL? anyway, good to know =).

> Thank you for the help, I will close this issue soon if no other problems will occur and maybe open new ones in case I need other help. :)

You're welcome =). Before closing, let me know if my changes & steps above works for you, maybe is better (and more convenient) to use than WSL.

---
Before I forget, I'll review this 'draft_windows' branch more carefully so that I can introduce these changes to the 'master', after all, it wasn't that complicated, right? =).

**Comment by smilexs4** [comment] 2020-10-28 23:00
Hi again,

> Natively or on WSL? anyway, good to know =).

On WSL, it created a .vscode folder in home directory with 4 json files including tasks.json.

> You're welcome =). Before closing, let me know if my changes & steps above works for you, maybe is better (and more convenient) to use than WSL.

It did work for the first try. :) I still have to set up Visual Studio to compile the right way, but hopefully I can manage to do that.

> Before I forget, I'll review this 'draft_windows' branch more carefully so that I can introduce these changes to the 'master', after all, it wasn't that complicated, right? =).

Might not be that complicated for you, but it would be impossible for me. ;P

Anyways, thank you again for all the help, hopefully using this library will be more optimal than any node.js module and definitely simpler then other c++ libraries I tried before. :D

**Closed** 2020-11-27 21:31 UTC
